source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Updatra_Example', :exclusive => true do
  pod "Updatra", :path => "../"
end

target 'Updatra_Tests', :exclusive => true do
  pod "Updatra", :path => "../"

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end
